version: '3.4'

services:
  dominosremake-web:
    image: ${DOCKER_REGISTRY-}dominosremake-web
    build:
      context: ./src/server
      dockerfile: DominosRemake.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro