name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Docker image
      run: |
        docker build -f src/server/DominosRemake.Web/Dockerfile -t my-app .

    - name: Install Railway
      run: |
        curl -sL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
